export default {
  "fig1":[
  {
    "name":"海淀区",
    "value":{
      "num":2165,
      "avgPrice":"11200.46"
    }
  },
  {
    "name":"顺义区",
    "value":{
      "num":932,
      "avgPrice":"6317.49"
    }
  },
  {
    "name":"东城区",
    "value":{
      "num":246,
      "avgPrice":"10751.89"
    }
  },
  {
    "name":"丰台区",
    "value":{
      "num":2214,
      "avgPrice":"7230.20"
    }
  },
  {
    "name":"朝阳区",
    "value":{
      "num":5387,
      "avgPrice":"12297.06"
    }
  },
  {
    "name":"通州区",
    "value":{
      "num":1442,
      "avgPrice":"5257.93"
    }
  },
  {
    "name":"西城区",
    "value":{
      "num":1113,
      "avgPrice":"11323.82"
    }
  },
  {
    "name":"门头沟区",
    "value":{
      "num":584,
      "avgPrice":"3765.15"
    }
  },
  {
    "name":"大兴区",
    "value":{
      "num":1452,
      "avgPrice":"6227.74"
    }
  },
  {
    "name":"房山区",
    "value":{
      "num":694,
      "avgPrice":"3763.21"
    }
  },
  {
    "name":"石景山区",
    "value":{
      "num":514,
      "avgPrice":"6380.18"
    }
  },
  {
    "name":"昌平区",
    "value":{
      "num":1380,
      "avgPrice":"7973.69"
    }
  },
  {
    "name":"平谷区",
    "value":{
      "num":1,
      "avgPrice":"3500.00"
    }
  }],
  "fig2":[
  {
    "name":"<1500",
    "value":18
  },
  {
    "name":"1500-2500",
    "value":142
  },
  {
    "name":"2500-3500",
    "value":1257
  },
  {
    "name":"3500-5000",
    "value":4771
  },
  {
    "name":"5000-8000",
    "value":11800
  },
  {
    "name":"8000-10000",
    "value":13916
  },
  {
    "name":">10000",
    "value":18124
  }],
  "fig3":[
  {
    "name":"海淀",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":511
        },
        {
          "name":"二居",
          "value":942
        },
        {
          "name":"三居",
          "value":438
        },
        {
          "name":"四居及以上",
          "value":274
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":0
        },
        {
          "name":"20-50m2",
          "value":336
        },
        {
          "name":"50-80m2",
          "value":914
        },
        {
          "name":"80-110m2",
          "value":399
        },
        {
          "name":"110-150m2",
          "value":253
        },
        {
          "name":"150m2以上",
          "value":263
        }],
      "price":[
        {
          "name":"<1500",
          "value":1
        },
        {
          "name":"1500-2500",
          "value":0
        },
        {
          "name":"2500-3500",
          "value":1
        },
        {
          "name":"3500-5000",
          "value":56
        },
        {
          "name":"5000-8000",
          "value":985
        },
        {
          "name":"8000-10000",
          "value":407
        },
        {
          "name":">10000",
          "value":715
        }]
    }
  },
  {
    "name":"顺义",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":97
        },
        {
          "name":"二居",
          "value":361
        },
        {
          "name":"三居",
          "value":250
        },
        {
          "name":"四居及以上",
          "value":224
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":0
        },
        {
          "name":"20-50m2",
          "value":93
        },
        {
          "name":"50-80m2",
          "value":342
        },
        {
          "name":"80-110m2",
          "value":272
        },
        {
          "name":"110-150m2",
          "value":145
        },
        {
          "name":"150m2以上",
          "value":80
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":10
        },
        {
          "name":"2500-3500",
          "value":162
        },
        {
          "name":"3500-5000",
          "value":412
        },
        {
          "name":"5000-8000",
          "value":218
        },
        {
          "name":"8000-10000",
          "value":41
        },
        {
          "name":">10000",
          "value":89
        }]
    }
  },
  {
    "name":"东城",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":75
        },
        {
          "name":"二居",
          "value":110
        },
        {
          "name":"三居",
          "value":30
        },
        {
          "name":"四居及以上",
          "value":31
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":16
        },
        {
          "name":"20-50m2",
          "value":52
        },
        {
          "name":"50-80m2",
          "value":103
        },
        {
          "name":"80-110m2",
          "value":38
        },
        {
          "name":"110-150m2",
          "value":15
        },
        {
          "name":"150m2以上",
          "value":22
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":1
        },
        {
          "name":"2500-3500",
          "value":4
        },
        {
          "name":"3500-5000",
          "value":16
        },
        {
          "name":"5000-8000",
          "value":89
        },
        {
          "name":"8000-10000",
          "value":58
        },
        {
          "name":">10000",
          "value":78
        }]
    }
  },
  {
    "name":"丰台",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":563
        },
        {
          "name":"二居",
          "value":1014
        },
        {
          "name":"三居",
          "value":356
        },
        {
          "name":"四居及以上",
          "value":281
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":3
        },
        {
          "name":"20-50m2",
          "value":393
        },
        {
          "name":"50-80m2",
          "value":973
        },
        {
          "name":"80-110m2",
          "value":450
        },
        {
          "name":"110-150m2",
          "value":285
        },
        {
          "name":"150m2以上",
          "value":110
        }],
      "price":[
        {
          "name":"<1500",
          "value":1
        },
        {
          "name":"1500-2500",
          "value":1
        },
        {
          "name":"2500-3500",
          "value":31
        },
        {
          "name":"3500-5000",
          "value":480
        },
        {
          "name":"5000-8000",
          "value":1139
        },
        {
          "name":"8000-10000",
          "value":283
        },
        {
          "name":">10000",
          "value":279
        }]
    }
  },
  {
    "name":"朝阳",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":1455
        },
        {
          "name":"二居",
          "value":2143
        },
        {
          "name":"三居",
          "value":1074
        },
        {
          "name":"四居及以上",
          "value":715
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":4
        },
        {
          "name":"20-50m2",
          "value":646
        },
        {
          "name":"50-80m2",
          "value":2088
        },
        {
          "name":"80-110m2",
          "value":1075
        },
        {
          "name":"110-150m2",
          "value":738
        },
        {
          "name":"150m2以上",
          "value":836
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":0
        },
        {
          "name":"2500-3500",
          "value":9
        },
        {
          "name":"3500-5000",
          "value":217
        },
        {
          "name":"5000-8000",
          "value":2213
        },
        {
          "name":"8000-10000",
          "value":802
        },
        {
          "name":">10000",
          "value":2146
        }]
    }
  },
  {
    "name":"通州",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":334
        },
        {
          "name":"二居",
          "value":723
        },
        {
          "name":"三居",
          "value":254
        },
        {
          "name":"四居及以上",
          "value":131
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":1
        },
        {
          "name":"20-50m2",
          "value":111
        },
        {
          "name":"50-80m2",
          "value":530
        },
        {
          "name":"80-110m2",
          "value":557
        },
        {
          "name":"110-150m2",
          "value":166
        },
        {
          "name":"150m2以上",
          "value":77
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":1
        },
        {
          "name":"2500-3500",
          "value":123
        },
        {
          "name":"3500-5000",
          "value":761
        },
        {
          "name":"5000-8000",
          "value":440
        },
        {
          "name":"8000-10000",
          "value":49
        },
        {
          "name":">10000",
          "value":68
        }]
    }
  },
  {
    "name":"西城",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":337
        },
        {
          "name":"二居",
          "value":509
        },
        {
          "name":"三居",
          "value":213
        },
        {
          "name":"四居及以上",
          "value":54
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":13
        },
        {
          "name":"20-50m2",
          "value":219
        },
        {
          "name":"50-80m2",
          "value":540
        },
        {
          "name":"80-110m2",
          "value":163
        },
        {
          "name":"110-150m2",
          "value":85
        },
        {
          "name":"150m2以上",
          "value":93
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":2
        },
        {
          "name":"2500-3500",
          "value":3
        },
        {
          "name":"3500-5000",
          "value":33
        },
        {
          "name":"5000-8000",
          "value":494
        },
        {
          "name":"8000-10000",
          "value":204
        },
        {
          "name":">10000",
          "value":377
        }]
    }
  },
  {
    "name":"门头沟",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":82
        },
        {
          "name":"二居",
          "value":237
        },
        {
          "name":"三居",
          "value":133
        },
        {
          "name":"四居及以上",
          "value":132
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":0
        },
        {
          "name":"20-50m2",
          "value":120
        },
        {
          "name":"50-80m2",
          "value":247
        },
        {
          "name":"80-110m2",
          "value":153
        },
        {
          "name":"110-150m2",
          "value":51
        },
        {
          "name":"150m2以上",
          "value":13
        }],
      "price":[
        {
          "name":"<1500",
          "value":3
        },
        {
          "name":"1500-2500",
          "value":48
        },
        {
          "name":"2500-3500",
          "value":272
        },
        {
          "name":"3500-5000",
          "value":179
        },
        {
          "name":"5000-8000",
          "value":66
        },
        {
          "name":"8000-10000",
          "value":7
        },
        {
          "name":">10000",
          "value":9
        }]
    }
  },
  {
    "name":"大兴",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":204
        },
        {
          "name":"二居",
          "value":755
        },
        {
          "name":"三居",
          "value":309
        },
        {
          "name":"四居及以上",
          "value":184
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":0
        },
        {
          "name":"20-50m2",
          "value":121
        },
        {
          "name":"50-80m2",
          "value":473
        },
        {
          "name":"80-110m2",
          "value":534
        },
        {
          "name":"110-150m2",
          "value":214
        },
        {
          "name":"150m2以上",
          "value":110
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":1
        },
        {
          "name":"2500-3500",
          "value":104
        },
        {
          "name":"3500-5000",
          "value":677
        },
        {
          "name":"5000-8000",
          "value":434
        },
        {
          "name":"8000-10000",
          "value":82
        },
        {
          "name":">10000",
          "value":154
        }]
    }
  },
  {
    "name":"房山",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":46
        },
        {
          "name":"二居",
          "value":256
        },
        {
          "name":"三居",
          "value":157
        },
        {
          "name":"四居及以上",
          "value":235
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":0
        },
        {
          "name":"20-50m2",
          "value":156
        },
        {
          "name":"50-80m2",
          "value":193
        },
        {
          "name":"80-110m2",
          "value":264
        },
        {
          "name":"110-150m2",
          "value":64
        },
        {
          "name":"150m2以上",
          "value":17
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":47
        },
        {
          "name":"2500-3500",
          "value":314
        },
        {
          "name":"3500-5000",
          "value":237
        },
        {
          "name":"5000-8000",
          "value":83
        },
        {
          "name":"8000-10000",
          "value":5
        },
        {
          "name":">10000",
          "value":8
        }]
    }
  },
  {
    "name":"石景山",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":116
        },
        {
          "name":"二居",
          "value":275
        },
        {
          "name":"三居",
          "value":63
        },
        {
          "name":"四居及以上",
          "value":60
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":1
        },
        {
          "name":"20-50m2",
          "value":72
        },
        {
          "name":"50-80m2",
          "value":289
        },
        {
          "name":"80-110m2",
          "value":95
        },
        {
          "name":"110-150m2",
          "value":44
        },
        {
          "name":"150m2以上",
          "value":13
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":1
        },
        {
          "name":"2500-3500",
          "value":2
        },
        {
          "name":"3500-5000",
          "value":168
        },
        {
          "name":"5000-8000",
          "value":254
        },
        {
          "name":"8000-10000",
          "value":43
        },
        {
          "name":">10000",
          "value":46
        }]
    }
  },
  {
    "name":"昌平",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":148
        },
        {
          "name":"二居",
          "value":554
        },
        {
          "name":"三居",
          "value":327
        },
        {
          "name":"四居及以上",
          "value":351
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":12
        },
        {
          "name":"20-50m2",
          "value":122
        },
        {
          "name":"50-80m2",
          "value":341
        },
        {
          "name":"80-110m2",
          "value":464
        },
        {
          "name":"110-150m2",
          "value":230
        },
        {
          "name":"150m2以上",
          "value":211
        }],
      "price":[
        {
          "name":"<1500",
          "value":13
        },
        {
          "name":"1500-2500",
          "value":12
        },
        {
          "name":"2500-3500",
          "value":90
        },
        {
          "name":"3500-5000",
          "value":277
        },
        {
          "name":"5000-8000",
          "value":614
        },
        {
          "name":"8000-10000",
          "value":135
        },
        {
          "name":">10000",
          "value":239
        }]
    }
  },
  {
    "name":"平谷",
    "value":{
      "roomType":[
        {
          "name":"一居",
          "value":0
        },
        {
          "name":"二居",
          "value":0
        },
        {
          "name":"三居",
          "value":1
        },
        {
          "name":"四居及以上",
          "value":0
        }],
      "areaSize":[
        {
          "name":"20m2以下",
          "value":0
        },
        {
          "name":"20-50m2",
          "value":0
        },
        {
          "name":"50-80m2",
          "value":0
        },
        {
          "name":"80-110m2",
          "value":0
        },
        {
          "name":"110-150m2",
          "value":1
        },
        {
          "name":"150m2以上",
          "value":0
        }],
      "price":[
        {
          "name":"<1500",
          "value":0
        },
        {
          "name":"1500-2500",
          "value":0
        },
        {
          "name":"2500-3500",
          "value":0
        },
        {
          "name":"3500-5000",
          "value":1
        },
        {
          "name":"5000-8000",
          "value":0
        },
        {
          "name":"8000-10000",
          "value":0
        },
        {
          "name":">10000",
          "value":0
        }]
    }
  }]
}
