export default {
  "fig1":[
    {
      "name":"海淀区",
      "value":{
        "num":6926,
        "avgPrice":87657.05457695639
      }
    },
    {
      "name":"顺义区",
      "value":{
        "num":2930,
        "avgPrice":42539
      }
    },
    {
      "name":"东城区",
      "value":{
        "num":707,
        "avgPrice":102150.86562942009
      }
    },
    {
      "name":"怀柔区",
      "value":{
        "num":8,
        "avgPrice":37611.875
      }
    },
    {
      "name":"丰台区",
      "value":{
        "num":6723,
        "avgPrice":62430.762308493235
      }
    },
    {
      "name":"朝阳区",
      "value":{
        "num":16274,
        "avgPrice":70986.87446233256
      }
    },
    {
      "name":"通州区",
      "value":{
        "num":2313,
        "avgPrice":47894.50453955901
      }
    },
    {
      "name":"西城区",
      "value":{
        "num":2057,
        "avgPrice":108608.80845892076
      }
    },
    {
      "name":"大兴区",
      "value":{
        "num":4235,
        "avgPrice":46834.02975206612
      }
    },
    {
      "name":"房山区",
      "value":{
        "num":2758,
        "avgPrice":33605.176939811456
      }
    },
    {
      "name":"石景山区",
      "value":{
        "num":1505,
        "avgPrice":56466.10232558139
      }
    },
    {
      "name":"昌平区",
      "value":{
        "num":6019,
        "avgPrice":46906.894500747636
      }
    },
    {
      "name":"门头沟区",
      "value":{
        "num":873,
        "avgPrice":40256.239404352804
      }
    },
    {
      "name":"延庆县",
      "value":{
        "num":6,
        "avgPrice":40180.5
      }
    },
    {
      "name":"平谷区",
      "value":{
        "num":57,
        "avgPrice":25469.456140350878
      }
    },
    {
      "name":"密云县",
      "value":{
        "num":50,
        "avgPrice":27081.44
      }
    }],
  "fig2":[
    {
      "name":"200万以下",
      "value":1299
    },
    {
      "name":"200-300万",
      "value":6675
    },
    {
      "name":"300-500万",
      "value":25587
    },
    {
      "name":"500-700万",
      "value":37478
    },
    {
      "name":"700-1000万",
      "value":45891
    },
    {
      "name":"1000万以上",
      "value":53441
    }],
  "fig3":[
    {
      "name":"西四",
      "value":138219.4
    },
    {
      "name":"德胜门",
      "value":136098.06451612903
    },
    {
      "name":"金融街",
      "value":131621.3918918919
    },
    {
      "name":"地安门",
      "value":129408.76
    },
    {
      "name":"西单",
      "value":127652.76190476191
    },
    {
      "name":"宣武门",
      "value":127164.88059701493
    },
    {
      "name":"交道口",
      "value":126663.7
    },
    {
      "name":"东单",
      "value":123805.54545454546
    },
    {
      "name":"万柳",
      "value":122467.01716738197
    },
    {
      "name":"月坛",
      "value":121796.44886363637
    },
    {
      "name":"六铺炕",
      "value":121388.12299465241
    },
    {
      "name":"木樨地",
      "value":118092.70714285714
    },
    {
      "name":"太阳宫",
      "value":115950.37967914439
    },
    {
      "name":"马甸",
      "value":114284.63688760807
    },
    {
      "name":"灯市口",
      "value":114053.39622641509
    },
    {
      "name":"陶然亭",
      "value":112438.12621359223
    },
    {
      "name":"金宝街",
      "value":110856.45
    },
    {
      "name":"朝阳门内",
      "value":110458.47029702971
    },
    {
      "name":"阜成门",
      "value":108771.7564102564
    },
    {
      "name":"官园",
      "value":108185.9420289855
    },
    {
      "name":"车公庄",
      "value":107778.30232558139
    },
    {
      "name":"安定门",
      "value":102424.23243243243
    },
    {
      "name":"前门",
      "value":102307.25
    },
    {
      "name":"万寿路",
      "value":102115.30357142857
    },
    {
      "name":"中关村",
      "value":101948.1835443038
    },
    {
      "name":"世纪城",
      "value":100074.21538461538
    },
    {
      "name":"建国门内",
      "value":99330.98979591837
    },
    {
      "name":"右安门内",
      "value":99330.42446043165
    },
    {
      "name":"东四",
      "value":99181.08108108108
    },
    {
      "name":"双榆树",
      "value":98864.95945945945
    },
    {
      "name":"广安门",
      "value":98456.20716112532
    },
    {
      "name":"崇文门",
      "value":98250.35458167331
    },
    {
      "name":"东直门",
      "value":98215.54285714286
    },
    {
      "name":"东花市",
      "value":96001.34959349594
    },
    {
      "name":"长椿街",
      "value":95286.34042553192
    },
    {
      "name":"魏公村",
      "value":94933.484375
    },
    {
      "name":"五道口",
      "value":93623.65638766519
    },
    {
      "name":"厂洼",
      "value":93327.72413793103
    },
    {
      "name":"西直门",
      "value":92483.2319391635
    },
    {
      "name":"甘家口",
      "value":92330.88636363637
    },
    {
      "name":"知春路",
      "value":91823.43661971831
    },
    {
      "name":"牛街",
      "value":91674.00888888889
    },
    {
      "name":"天宁寺",
      "value":90826.92156862745
    },
    {
      "name":"白石桥",
      "value":90598.2
    },
    {
      "name":"新街口",
      "value":90266.68103448275
    },
    {
      "name":"苏州桥",
      "value":89991.70822281168
    },
    {
      "name":"东大桥",
      "value":89589.44047619047
    },
    {
      "name":"北太平庄",
      "value":89189.98076923077
    },
    {
      "name":"四季青",
      "value":89101.11698113207
    },
    {
      "name":"牡丹园",
      "value":88764.79695431472
    }],
  "fig4":[
    {
      "name":"海淀",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":1146
          },
          {
            "name":"二居",
            "value":3118
          },
          {
            "name":"三居",
            "value":1903
          },
          {
            "name":"四居及以上",
            "value":759
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":637
          },
          {
            "name":"50-80m2",
            "value":2932
          },
          {
            "name":"80-110m2",
            "value":1422
          },
          {
            "name":"110-150m2",
            "value":972
          },
          {
            "name":"150m2以上",
            "value":963
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":11
          },
          {
            "name":"1-2w",
            "value":3
          },
          {
            "name":"2-3w",
            "value":15
          },
          {
            "name":"3-4w",
            "value":64
          },
          {
            "name":"4-5w",
            "value":121
          },
          {
            "name":"5-6w",
            "value":321
          },
          {
            "name":"6-7w",
            "value":646
          },
          {
            "name":"7-8w",
            "value":1224
          },
          {
            "name":"8-9w",
            "value":1621
          },
          {
            "name":"9-10w",
            "value":1323
          },
          {
            "name":">10w",
            "value":1577
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":67
          },
          {
            "name":"200-300万",
            "value":100
          },
          {
            "name":"300-500万",
            "value":1500
          },
          {
            "name":"500-700万",
            "value":1951
          },
          {
            "name":"700-1000万",
            "value":1580
          },
          {
            "name":"1000万以上",
            "value":6902
          }]
      }
    },
    {
      "name":"顺义",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":244
          },
          {
            "name":"二居",
            "value":958
          },
          {
            "name":"三居",
            "value":949
          },
          {
            "name":"四居及以上",
            "value":779
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":135
          },
          {
            "name":"50-80m2",
            "value":645
          },
          {
            "name":"80-110m2",
            "value":826
          },
          {
            "name":"110-150m2",
            "value":598
          },
          {
            "name":"150m2以上",
            "value":726
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":6
          },
          {
            "name":"1-2w",
            "value":42
          },
          {
            "name":"2-3w",
            "value":256
          },
          {
            "name":"3-4w",
            "value":1094
          },
          {
            "name":"4-5w",
            "value":1005
          },
          {
            "name":"5-6w",
            "value":303
          },
          {
            "name":"6-7w",
            "value":102
          },
          {
            "name":"7-8w",
            "value":54
          },
          {
            "name":"8-9w",
            "value":28
          },
          {
            "name":"9-10w",
            "value":18
          },
          {
            "name":">10w",
            "value":22
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":156
          },
          {
            "name":"200-300万",
            "value":570
          },
          {
            "name":"300-500万",
            "value":1128
          },
          {
            "name":"500-700万",
            "value":466
          },
          {
            "name":"700-1000万",
            "value":208
          },
          {
            "name":"1000万以上",
            "value":2886
          }]
      }
    },
    {
      "name":"东城",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":120
          },
          {
            "name":"二居",
            "value":315
          },
          {
            "name":"三居",
            "value":202
          },
          {
            "name":"四居及以上",
            "value":70
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":68
          },
          {
            "name":"50-80m2",
            "value":335
          },
          {
            "name":"80-110m2",
            "value":146
          },
          {
            "name":"110-150m2",
            "value":91
          },
          {
            "name":"150m2以上",
            "value":67
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":0
          },
          {
            "name":"2-3w",
            "value":0
          },
          {
            "name":"3-4w",
            "value":1
          },
          {
            "name":"4-5w",
            "value":5
          },
          {
            "name":"5-6w",
            "value":23
          },
          {
            "name":"6-7w",
            "value":19
          },
          {
            "name":"7-8w",
            "value":58
          },
          {
            "name":"8-9w",
            "value":85
          },
          {
            "name":"9-10w",
            "value":120
          },
          {
            "name":">10w",
            "value":396
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":9
          },
          {
            "name":"200-300万",
            "value":4
          },
          {
            "name":"300-500万",
            "value":63
          },
          {
            "name":"500-700万",
            "value":195
          },
          {
            "name":"700-1000万",
            "value":251
          },
          {
            "name":"1000万以上",
            "value":700
          }]
      }
    },
    {
      "name":"怀柔",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":0
          },
          {
            "name":"二居",
            "value":1
          },
          {
            "name":"三居",
            "value":4
          },
          {
            "name":"四居及以上",
            "value":3
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":0
          },
          {
            "name":"50-80m2",
            "value":0
          },
          {
            "name":"80-110m2",
            "value":4
          },
          {
            "name":"110-150m2",
            "value":1
          },
          {
            "name":"150m2以上",
            "value":3
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":0
          },
          {
            "name":"2-3w",
            "value":2
          },
          {
            "name":"3-4w",
            "value":3
          },
          {
            "name":"4-5w",
            "value":3
          },
          {
            "name":"5-6w",
            "value":0
          },
          {
            "name":"6-7w",
            "value":0
          },
          {
            "name":"7-8w",
            "value":0
          },
          {
            "name":"8-9w",
            "value":0
          },
          {
            "name":"9-10w",
            "value":0
          },
          {
            "name":">10w",
            "value":0
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":0
          },
          {
            "name":"200-300万",
            "value":2
          },
          {
            "name":"300-500万",
            "value":3
          },
          {
            "name":"500-700万",
            "value":0
          },
          {
            "name":"700-1000万",
            "value":2
          },
          {
            "name":"1000万以上",
            "value":8
          }]
      }
    },
    {
      "name":"丰台",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":1420
          },
          {
            "name":"二居",
            "value":3152
          },
          {
            "name":"三居",
            "value":1714
          },
          {
            "name":"四居及以上",
            "value":437
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":656
          },
          {
            "name":"50-80m2",
            "value":2626
          },
          {
            "name":"80-110m2",
            "value":1858
          },
          {
            "name":"110-150m2",
            "value":1112
          },
          {
            "name":"150m2以上",
            "value":471
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":10
          },
          {
            "name":"1-2w",
            "value":12
          },
          {
            "name":"2-3w",
            "value":20
          },
          {
            "name":"3-4w",
            "value":219
          },
          {
            "name":"4-5w",
            "value":902
          },
          {
            "name":"5-6w",
            "value":2221
          },
          {
            "name":"6-7w",
            "value":1902
          },
          {
            "name":"7-8w",
            "value":683
          },
          {
            "name":"8-9w",
            "value":354
          },
          {
            "name":"9-10w",
            "value":205
          },
          {
            "name":">10w",
            "value":195
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":97
          },
          {
            "name":"200-300万",
            "value":633
          },
          {
            "name":"300-500万",
            "value":2825
          },
          {
            "name":"500-700万",
            "value":1725
          },
          {
            "name":"700-1000万",
            "value":1007
          },
          {
            "name":"1000万以上",
            "value":6693
          }]
      }
    },
    {
      "name":"朝阳",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":3344
          },
          {
            "name":"二居",
            "value":6896
          },
          {
            "name":"三居",
            "value":4343
          },
          {
            "name":"四居及以上",
            "value":1691
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":1244
          },
          {
            "name":"50-80m2",
            "value":5814
          },
          {
            "name":"80-110m2",
            "value":3841
          },
          {
            "name":"110-150m2",
            "value":2859
          },
          {
            "name":"150m2以上",
            "value":2516
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":36
          },
          {
            "name":"1-2w",
            "value":55
          },
          {
            "name":"2-3w",
            "value":29
          },
          {
            "name":"3-4w",
            "value":258
          },
          {
            "name":"4-5w",
            "value":1488
          },
          {
            "name":"5-6w",
            "value":3006
          },
          {
            "name":"6-7w",
            "value":3614
          },
          {
            "name":"7-8w",
            "value":3325
          },
          {
            "name":"8-9w",
            "value":2100
          },
          {
            "name":"9-10w",
            "value":1145
          },
          {
            "name":">10w",
            "value":1218
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":203
          },
          {
            "name":"200-300万",
            "value":753
          },
          {
            "name":"300-500万",
            "value":5237
          },
          {
            "name":"500-700万",
            "value":3760
          },
          {
            "name":"700-1000万",
            "value":3186
          },
          {
            "name":"1000万以上",
            "value":16177
          }]
      }
    },
    {
      "name":"通州",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":421
          },
          {
            "name":"二居",
            "value":1036
          },
          {
            "name":"三居",
            "value":575
          },
          {
            "name":"四居及以上",
            "value":281
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":114
          },
          {
            "name":"50-80m2",
            "value":687
          },
          {
            "name":"80-110m2",
            "value":866
          },
          {
            "name":"110-150m2",
            "value":377
          },
          {
            "name":"150m2以上",
            "value":269
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":9
          },
          {
            "name":"1-2w",
            "value":10
          },
          {
            "name":"2-3w",
            "value":38
          },
          {
            "name":"3-4w",
            "value":281
          },
          {
            "name":"4-5w",
            "value":1184
          },
          {
            "name":"5-6w",
            "value":577
          },
          {
            "name":"6-7w",
            "value":171
          },
          {
            "name":"7-8w",
            "value":29
          },
          {
            "name":"8-9w",
            "value":11
          },
          {
            "name":"9-10w",
            "value":1
          },
          {
            "name":">10w",
            "value":2
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":57
          },
          {
            "name":"200-300万",
            "value":316
          },
          {
            "name":"300-500万",
            "value":1196
          },
          {
            "name":"500-700万",
            "value":465
          },
          {
            "name":"700-1000万",
            "value":156
          },
          {
            "name":"1000万以上",
            "value":2297
          }]
      }
    },
    {
      "name":"西城",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":346
          },
          {
            "name":"二居",
            "value":952
          },
          {
            "name":"三居",
            "value":622
          },
          {
            "name":"四居及以上",
            "value":137
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":140
          },
          {
            "name":"50-80m2",
            "value":1067
          },
          {
            "name":"80-110m2",
            "value":423
          },
          {
            "name":"110-150m2",
            "value":213
          },
          {
            "name":"150m2以上",
            "value":214
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":1
          },
          {
            "name":"2-3w",
            "value":0
          },
          {
            "name":"3-4w",
            "value":0
          },
          {
            "name":"4-5w",
            "value":6
          },
          {
            "name":"5-6w",
            "value":26
          },
          {
            "name":"6-7w",
            "value":48
          },
          {
            "name":"7-8w",
            "value":98
          },
          {
            "name":"8-9w",
            "value":260
          },
          {
            "name":"9-10w",
            "value":333
          },
          {
            "name":">10w",
            "value":1285
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":1
          },
          {
            "name":"200-300万",
            "value":1
          },
          {
            "name":"300-500万",
            "value":115
          },
          {
            "name":"500-700万",
            "value":576
          },
          {
            "name":"700-1000万",
            "value":779
          },
          {
            "name":"1000万以上",
            "value":2056
          }]
      }
    },
    {
      "name":"大兴",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":472
          },
          {
            "name":"二居",
            "value":1918
          },
          {
            "name":"三居",
            "value":1264
          },
          {
            "name":"四居及以上",
            "value":581
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":236
          },
          {
            "name":"50-80m2",
            "value":1199
          },
          {
            "name":"80-110m2",
            "value":1512
          },
          {
            "name":"110-150m2",
            "value":742
          },
          {
            "name":"150m2以上",
            "value":546
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":15
          },
          {
            "name":"1-2w",
            "value":2
          },
          {
            "name":"2-3w",
            "value":172
          },
          {
            "name":"3-4w",
            "value":974
          },
          {
            "name":"4-5w",
            "value":1812
          },
          {
            "name":"5-6w",
            "value":720
          },
          {
            "name":"6-7w",
            "value":319
          },
          {
            "name":"7-8w",
            "value":155
          },
          {
            "name":"8-9w",
            "value":55
          },
          {
            "name":"9-10w",
            "value":6
          },
          {
            "name":">10w",
            "value":5
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":59
          },
          {
            "name":"200-300万",
            "value":819
          },
          {
            "name":"300-500万",
            "value":2015
          },
          {
            "name":"500-700万",
            "value":723
          },
          {
            "name":"700-1000万",
            "value":358
          },
          {
            "name":"1000万以上",
            "value":4217
          }]
      }
    },
    {
      "name":"房山",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":153
          },
          {
            "name":"二居",
            "value":1195
          },
          {
            "name":"三居",
            "value":952
          },
          {
            "name":"四居及以上",
            "value":458
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":184
          },
          {
            "name":"50-80m2",
            "value":466
          },
          {
            "name":"80-110m2",
            "value":1255
          },
          {
            "name":"110-150m2",
            "value":587
          },
          {
            "name":"150m2以上",
            "value":266
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":34
          },
          {
            "name":"1-2w",
            "value":89
          },
          {
            "name":"2-3w",
            "value":837
          },
          {
            "name":"3-4w",
            "value":1151
          },
          {
            "name":"4-5w",
            "value":576
          },
          {
            "name":"5-6w",
            "value":49
          },
          {
            "name":"6-7w",
            "value":21
          },
          {
            "name":"7-8w",
            "value":1
          },
          {
            "name":"8-9w",
            "value":0
          },
          {
            "name":"9-10w",
            "value":0
          },
          {
            "name":">10w",
            "value":0
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":324
          },
          {
            "name":"200-300万",
            "value":896
          },
          {
            "name":"300-500万",
            "value":1218
          },
          {
            "name":"500-700万",
            "value":217
          },
          {
            "name":"700-1000万",
            "value":75
          },
          {
            "name":"1000万以上",
            "value":2666
          }]
      }
    },
    {
      "name":"石景山",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":184
          },
          {
            "name":"二居",
            "value":870
          },
          {
            "name":"三居",
            "value":352
          },
          {
            "name":"四居及以上",
            "value":99
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":115
          },
          {
            "name":"50-80m2",
            "value":660
          },
          {
            "name":"80-110m2",
            "value":463
          },
          {
            "name":"110-150m2",
            "value":220
          },
          {
            "name":"150m2以上",
            "value":47
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":15
          },
          {
            "name":"2-3w",
            "value":10
          },
          {
            "name":"3-4w",
            "value":22
          },
          {
            "name":"4-5w",
            "value":499
          },
          {
            "name":"5-6w",
            "value":492
          },
          {
            "name":"6-7w",
            "value":247
          },
          {
            "name":"7-8w",
            "value":128
          },
          {
            "name":"8-9w",
            "value":51
          },
          {
            "name":"9-10w",
            "value":31
          },
          {
            "name":">10w",
            "value":10
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":31
          },
          {
            "name":"200-300万",
            "value":286
          },
          {
            "name":"300-500万",
            "value":652
          },
          {
            "name":"500-700万",
            "value":275
          },
          {
            "name":"700-1000万",
            "value":186
          },
          {
            "name":"1000万以上",
            "value":1487
          }]
      }
    },
    {
      "name":"昌平",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":504
          },
          {
            "name":"二居",
            "value":2429
          },
          {
            "name":"三居",
            "value":1953
          },
          {
            "name":"四居及以上",
            "value":1133
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":272
          },
          {
            "name":"50-80m2",
            "value":1180
          },
          {
            "name":"80-110m2",
            "value":1861
          },
          {
            "name":"110-150m2",
            "value":1448
          },
          {
            "name":"150m2以上",
            "value":1258
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":26
          },
          {
            "name":"1-2w",
            "value":21
          },
          {
            "name":"2-3w",
            "value":389
          },
          {
            "name":"3-4w",
            "value":1748
          },
          {
            "name":"4-5w",
            "value":1910
          },
          {
            "name":"5-6w",
            "value":971
          },
          {
            "name":"6-7w",
            "value":464
          },
          {
            "name":"7-8w",
            "value":272
          },
          {
            "name":"8-9w",
            "value":102
          },
          {
            "name":"9-10w",
            "value":52
          },
          {
            "name":">10w",
            "value":64
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":229
          },
          {
            "name":"200-300万",
            "value":625
          },
          {
            "name":"300-500万",
            "value":2620
          },
          {
            "name":"500-700万",
            "value":1426
          },
          {
            "name":"700-1000万",
            "value":575
          },
          {
            "name":"1000万以上",
            "value":5978
          }]
      }
    },
    {
      "name":"门头沟",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":72
          },
          {
            "name":"二居",
            "value":502
          },
          {
            "name":"三居",
            "value":209
          },
          {
            "name":"四居及以上",
            "value":90
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":45
          },
          {
            "name":"50-80m2",
            "value":265
          },
          {
            "name":"80-110m2",
            "value":332
          },
          {
            "name":"110-150m2",
            "value":141
          },
          {
            "name":"150m2以上",
            "value":90
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":3
          },
          {
            "name":"2-3w",
            "value":40
          },
          {
            "name":"3-4w",
            "value":450
          },
          {
            "name":"4-5w",
            "value":321
          },
          {
            "name":"5-6w",
            "value":37
          },
          {
            "name":"6-7w",
            "value":7
          },
          {
            "name":"7-8w",
            "value":7
          },
          {
            "name":"8-9w",
            "value":2
          },
          {
            "name":"9-10w",
            "value":4
          },
          {
            "name":">10w",
            "value":2
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":50
          },
          {
            "name":"200-300万",
            "value":321
          },
          {
            "name":"300-500万",
            "value":313
          },
          {
            "name":"500-700万",
            "value":110
          },
          {
            "name":"700-1000万",
            "value":41
          },
          {
            "name":"1000万以上",
            "value":870
          }]
      }
    },
    {
      "name":"延庆",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":0
          },
          {
            "name":"二居",
            "value":1
          },
          {
            "name":"三居",
            "value":0
          },
          {
            "name":"四居及以上",
            "value":5
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":0
          },
          {
            "name":"50-80m2",
            "value":0
          },
          {
            "name":"80-110m2",
            "value":1
          },
          {
            "name":"110-150m2",
            "value":0
          },
          {
            "name":"150m2以上",
            "value":5
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":0
          },
          {
            "name":"2-3w",
            "value":0
          },
          {
            "name":"3-4w",
            "value":3
          },
          {
            "name":"4-5w",
            "value":2
          },
          {
            "name":"5-6w",
            "value":1
          },
          {
            "name":"6-7w",
            "value":0
          },
          {
            "name":"7-8w",
            "value":0
          },
          {
            "name":"8-9w",
            "value":0
          },
          {
            "name":"9-10w",
            "value":0
          },
          {
            "name":">10w",
            "value":0
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":0
          },
          {
            "name":"200-300万",
            "value":1
          },
          {
            "name":"300-500万",
            "value":0
          },
          {
            "name":"500-700万",
            "value":0
          },
          {
            "name":"700-1000万",
            "value":2
          },
          {
            "name":"1000万以上",
            "value":6
          }]
      }
    },
    {
      "name":"平谷",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":6
          },
          {
            "name":"二居",
            "value":17
          },
          {
            "name":"三居",
            "value":29
          },
          {
            "name":"四居及以上",
            "value":5
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":0
          },
          {
            "name":"50-80m2",
            "value":7
          },
          {
            "name":"80-110m2",
            "value":26
          },
          {
            "name":"110-150m2",
            "value":15
          },
          {
            "name":"150m2以上",
            "value":9
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":1
          },
          {
            "name":"2-3w",
            "value":53
          },
          {
            "name":"3-4w",
            "value":3
          },
          {
            "name":"4-5w",
            "value":0
          },
          {
            "name":"5-6w",
            "value":0
          },
          {
            "name":"6-7w",
            "value":0
          },
          {
            "name":"7-8w",
            "value":0
          },
          {
            "name":"8-9w",
            "value":0
          },
          {
            "name":"9-10w",
            "value":0
          },
          {
            "name":">10w",
            "value":0
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":6
          },
          {
            "name":"200-300万",
            "value":31
          },
          {
            "name":"300-500万",
            "value":16
          },
          {
            "name":"500-700万",
            "value":0
          },
          {
            "name":"700-1000万",
            "value":3
          },
          {
            "name":"1000万以上",
            "value":57
          }]
      }
    },
    {
      "name":"密云",
      "value":{
        "roomType":[
          {
            "name":"一居",
            "value":1
          },
          {
            "name":"二居",
            "value":17
          },
          {
            "name":"三居",
            "value":20
          },
          {
            "name":"四居及以上",
            "value":12
          }],
        "areaSize":[
          {
            "name":"50m2以下",
            "value":0
          },
          {
            "name":"50-80m2",
            "value":6
          },
          {
            "name":"80-110m2",
            "value":13
          },
          {
            "name":"110-150m2",
            "value":14
          },
          {
            "name":"150m2以上",
            "value":17
          }],
        "unitPrice":[
          {
            "name":"<1w",
            "value":0
          },
          {
            "name":"1-2w",
            "value":10
          },
          {
            "name":"2-3w",
            "value":32
          },
          {
            "name":"3-4w",
            "value":6
          },
          {
            "name":"4-5w",
            "value":0
          },
          {
            "name":"5-6w",
            "value":1
          },
          {
            "name":"6-7w",
            "value":0
          },
          {
            "name":"7-8w",
            "value":0
          },
          {
            "name":"8-9w",
            "value":0
          },
          {
            "name":"9-10w",
            "value":0
          },
          {
            "name":">10w",
            "value":1
          }],
        "totalPrice":[
          {
            "name":"200万以下",
            "value":10
          },
          {
            "name":"200-300万",
            "value":18
          },
          {
            "name":"300-500万",
            "value":11
          },
          {
            "name":"500-700万",
            "value":2
          },
          {
            "name":"700-1000万",
            "value":4
          },
          {
            "name":"1000万以上",
            "value":50
          }]
      }
    }]
}
